import NextAuth, { AuthOptions, getServerSession } from 'next-auth'
import Providers from 'next-auth/providers'
import { NextApiRequest, NextApiResponse } from 'next'
import DiscordProvider from 'next-auth/providers/discord'
import { OAuthConfig, OAuthUserConfig } from 'next-auth/providers'
import EmailProvider from 'next-auth/providers/email'
import GitHubProvider from 'next-auth/providers/github'
import GoogleProvider from 'next-auth/providers/google'
